### ISSUE TITLE
libexpat not packaged with linux wheels?

### ISSUE THREAD

**Issue by mathause** [sgillies/rasterio-wheels#136] opened 2024-11-12 08:26 UTC
It looks like libexpat is not packaged in linux wheels. However, from `build_expat` I would expect it to be - or do I interpret the `IS_OSX` flag wrong?

https://github.com/rasterio/rasterio-wheels/blob/c04fa87905fcf5b3fed053f6eb14d004b5554cca/config.sh#L155

Why is that relevant? Apparently some linux docker images stopped shipping libexpat (see docker-library/python#984) so importing rasterio fails in these containers.

**Comment by vincentsarago** [comment] 2024-11-12 08:54
I also just experienced it with AWS Lambda python 3.12, but I've not yet be able to create a simple reproductible example https://github.com/developmentseed/titiler-md-demo/issues/3

**Comment by AdelImamovic** [comment] 2024-11-12 12:36
Code to reproduce the issue: 

`podman pull docker.io/library/python:3.10-slim` # same with py311
`podman run python:3.10-slim sh -c "pip install rasterio && python -c 'import rasterio'"`

**Comment by sgillies** [comment] 2024-11-12 14:57
Thanks for the report @mathause ! I don't think I'll do anything about it just for these particular images.

Keep in mind that the rasterio wheels are mostly for testing purposes. I don't put them into production because they lack features and some of the library versions are a little old.

**Comment by mathause** [comment] 2024-11-12 15:13
Thanks for your answer. So what's the recommendation? Using conda? Or building locally?

It's obviously fair enough that the wheels should not be used for production - but where could I see that? Is that in the documentation? (And just as a comment: it's quite the recommendation for the individual user to know which package on the stack is usable and which is not. Especially if it had recent versions on pypi.)

**Comment by vincentsarago** [comment] 2024-11-27 16:57
this was also reported in https://github.com/rasterio/rasterio/discussions/3257#discussioncomment-11385860 and is linked to https://github.com/docker-library/python/issues/989

@mathause the easiest thing to do is to install libexpat 

```
apt update && apt install -y libexpat1
```

**Comment by sgillies** [comment] 2024-11-27 17:17
Thanks @vincentsarago ! I'll close this as it is all in the hands of the slim image maintainers.

It's not surprising that rasterio wheels users saw this first. Rasterio's C dependencies are probably the most numerous of any publicly published wheels.

**Closed as completed by sgillies** 2024-11-27 17:17 UTC
