### ISSUE TITLE
curl 7.54.0 not building as before

### ISSUE THREAD

**Issue by sgillies** [sgillies/rasterio-wheels#18] opened 2019-01-27 23:59 UTC
When we built wheels for 1.0.13, they included our custom built curl 7.54.0, but in the 1.0.14 wheel builds this curl was missed and the container's curl 7.61 was picked up instead. Problematic in 2 ways: there are bugs between GDAL and recent curl versions, and our nghttp2 library is not included.

It's difficult to figure out what's wrong with the curl build due to lack of logging, but I'm digging in a little this evening. I may not be able to sort this out until later in the week @vincentsarago .

**Comment by vincentsarago** [comment] 2019-01-28 00:53
Thanks @sgillies,
Yeah I've been able to fully understand what was going on with the few logging produced by travis+multibuild. 

About the bug in Curl I think it was fixed in v 7.63 (https://github.com/curl/curl/commit/2c15693a3c355d8296a1828123a864397296460b) so we should be able to build with this version

**Comment by sgillies** [comment] 2019-01-28 16:00
This is fixed. Permanently, I hope! From the Travis build log https://api.travis-ci.com/v3/job/173309211/log.txt:

```
  4116192  2019-01-28 00:28   rasterio/.libs/libhdf5-2d94a66d.so.101.1.0
   376744  2019-01-28 00:27   rasterio/.libs/libopenjp2-8f6da918.so.2.3.0
    37712  2019-01-28 00:28   rasterio/.libs/libaec-2147abcd.so.0.0.4
   182032  2019-01-28 00:28   rasterio/.libs/libhdf5_hl-d68fbc5b.so.100.1.0
    13240  2019-01-28 00:28   rasterio/.libs/libsz-1c7dd0cf.so.2.0.1
    60792  2019-01-28 00:28   rasterio/.libs/libjson-c-5f02f62c.so.2.0.2
  3144312  2019-01-28 00:28   rasterio/.libs/libcurl-e8503455.so.4.5.0
   580440  2019-01-28 00:27   rasterio/.libs/libproj-bd876d1a.so.12.0.0
   224232  2019-01-28 00:27   rasterio/.libs/libexpat-09c47d4c.so.1.6.8
  4883424  2019-01-28 00:27   rasterio/.libs/libgeos-3-cd838e67.6.2.so
101353264  2019-01-28 00:28   rasterio/.libs/libgdal-c9384152.so.20.5.0
   431816  2019-01-28 00:28   rasterio/.libs/libgeos_c-595de9d4.so.1.10.2
   279824  2019-01-28 00:28   rasterio/.libs/libpng16-898afbbd.so.16.35.0
  1876336  2019-01-28 00:28   rasterio/.libs/libnetcdf-24686c8b.so.11.0.4
   344704  2019-01-28 00:28   rasterio/.libs/libjpeg-3fe7dfc0.so.9.3.0
   776912  2019-01-28 00:27   rasterio/.libs/libwebp-8ccd29fd.so.7.0.2
   203512  2019-01-28 00:28   rasterio/.libs/libnghttp2-11cb20b8.so.14.17.1
  1267504  2019-01-28 00:28   rasterio/.libs/libsqlite3-fdd57a2d.so.0.8.6
    87848  2019-01-28 00:28   rasterio/.libs/libz-a147dcb0.so.1.2.3
```

**Comment by vincentsarago** [comment] 2019-01-28 16:01
nice! thanks @sgillies

**Comment by vincentsarago** [comment] 2019-01-28 17:01
confirmed 1.0.15 fixe worked  🙏 
```
ldd libgdal-c9384152.so.20.5.0
	linux-vdso.so.1 =>  (0x00007fffb41fe000)
	libproj-bd876d1a.so.12.0.0 => /var/lang/lib/python3.6/site-packages/rasterio/.libs/././libproj-bd876d1a.so.12.0.0 (0x00007f908990d000)
	libjson-c-5f02f62c.so.2.0.2 => /var/lang/lib/python3.6/site-packages/rasterio/.libs/././libjson-c-5f02f62c.so.2.0.2 (0x00007f90896ff000)
	libgeos_c-595de9d4.so.1.10.2 => /var/lang/lib/python3.6/site-packages/rasterio/.libs/././libgeos_c-595de9d4.so.1.10.2 (0x00007f9089496000)
	libwebp-8ccd29fd.so.7.0.2 => /var/lang/lib/python3.6/site-packages/rasterio/.libs/././libwebp-8ccd29fd.so.7.0.2 (0x00007f90891d6000)
	libsqlite3-fdd57a2d.so.0.8.6 => /var/lang/lib/python3.6/site-packages/rasterio/.libs/././libsqlite3-fdd57a2d.so.0.8.6 (0x00007f9088ea0000)
	libexpat-09c47d4c.so.1.6.8 => /var/lang/lib/python3.6/site-packages/rasterio/.libs/././libexpat-09c47d4c.so.1.6.8 (0x00007f9088c6a000)
	libopenjp2-8f6da918.so.2.3.0 => /var/lang/lib/python3.6/site-packages/rasterio/.libs/././libopenjp2-8f6da918.so.2.3.0 (0x00007f9088a0e000)
	libnetcdf-24686c8b.so.11.0.4 => /var/lang/lib/python3.6/site-packages/rasterio/.libs/././libnetcdf-24686c8b.so.11.0.4 (0x00007f9085635000)
	libhdf5-2d94a66d.so.101.1.0 => /var/lang/lib/python3.6/site-packages/rasterio/.libs/././libhdf5-2d94a66d.so.101.1.0 (0x00007f9085046000)
	libjpeg-3fe7dfc0.so.9.3.0 => /var/lang/lib/python3.6/site-packages/rasterio/.libs/././libjpeg-3fe7dfc0.so.9.3.0 (0x00007f9084df2000)
	libpng16-898afbbd.so.16.35.0 => /var/lang/lib/python3.6/site-packages/rasterio/.libs/././libpng16-898afbbd.so.16.35.0 (0x00007f9084bad000)
	libz-a147dcb0.so.1.2.3 => /var/lang/lib/python3.6/site-packages/rasterio/.libs/././libz-a147dcb0.so.1.2.3 (0x00007f9084998000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f908477c000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f9084574000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f9084370000)
	libcurl-e8503455.so.4.5.0 => /var/lang/lib/python3.6/site-packages/rasterio/.libs/././libcurl-e8503455.so.4.5.0 (0x00007f9083ebb000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f9083bb6000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f90838b4000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f90834f0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f908f7cb000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f90832da000)
	libgeos-3-cd838e67.6.2.so => /var/lang/lib/python3.6/site-packages/rasterio/.libs/./././libgeos-3-cd838e67.6.2.so (0x00007f9082c32000)
	libhdf5_hl-d68fbc5b.so.100.1.0 => /var/lang/lib/python3.6/site-packages/rasterio/.libs/./././libhdf5_hl-d68fbc5b.so.100.1.0 (0x00007f9082a05000)
	libsz-1c7dd0cf.so.2.0.1 => /var/lang/lib/python3.6/site-packages/rasterio/.libs/./././libsz-1c7dd0cf.so.2.0.1 (0x00007f9082801000)
	libaec-2147abcd.so.0.0.4 => /var/lang/lib/python3.6/site-packages/rasterio/.libs/./././libaec-2147abcd.so.0.0.4 (0x00007f90825f8000)
	libnghttp2-11cb20b8.so.14.17.1 => /var/lang/lib/python3.6/site-packages/rasterio/.libs/./././libnghttp2-11cb20b8.so.14.17.1 (0x00007f90823c6000)
```

**Comment by vincentsarago** [comment] 2019-01-28 17:14
@sgillies I'm sorry but there seems to be a problem with lib curl still: 

```
bash-4.2# ldd libcurl-e8503455.so.4.5.0
	linux-vdso.so.1 =>  (0x00007fffab56e000)
	libz-a147dcb0.so.1.2.3 => not found
	librt.so.1 => /lib64/librt.so.1 (0x00007f38f5696000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f38f5492000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f38f5276000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f38f4eb2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f38f5d53000)
```
and when running some code I get: 
`CPLE_NotSupported in HTTP/2 not available in this build of Curl. It needs to be built against nghttp2`

**Comment by sgillies** [comment] 2019-01-28 17:35
I see this too

```
$ GDAL_HTTP_VERSION=2 GDAL_CURL_VERBOSE=1 rio info s3://remotepixel-pub/cbers/CBERS_4_MUX_20160416_217_063_L2_BAND5.tif
WARNING:rasterio._env:CPLE_NotSupported in HTTP/2 not available in this build of Curl. It needs to be built against nghttp2
{"blockxsize": 256, "blockysize": 256, "bounds": [361320.0, 3588860.0, 509460.0, 3731360.0], "colorinterp": ["gray"], "compress": "deflate", "count": 1, "crs": "EPSG:32615", "descriptions": [null], "driver": "GTiff", "dtype": "uint8", "height": 7125, "indexes": [1], "interleave": "band", "lnglat": [-93.69223890855305, 33.07766525638994], "mask_flags": [["nodata"]], "nodata": 0.0, "res": [20.0, 20.0], "shape": [7125, 7407], "tiled": true, "transform": [20.0, 0.0, 361320.0, 0.0, -20.0, 3731360.0, 0.0, 0.0, 1.0], "units": [null], "width": 7407}
```

As well as this in the logs (with `rio -vvv info ...`)

```
DEBUG:rasterio._env:CPLE_None in HTTP: libcurl/7.61.1 OpenSSL/1.0.2q zlib/1.2.11
DEBUG:rasterio._env:CPLE_None in HTTP: GDAL was built against curl 7.54.0, but is running against 7.61.1.
WARNING:rasterio._env:CPLE_NotSupported in HTTP/2 not available in this build of Curl. It needs to be built against nghttp2
```

That extra curl 7.61 in the wheel build container strikes again!

**Comment by vincentsarago** [comment] 2019-01-28 17:41
🤔 this means that your gdal build is not fetching libcurl shipped with your wheel which is strange. 

ref: https://github.com/RemotePixel/amazonlinux-gdal/issues/7#issuecomment-457066719

**Comment by sgillies** [comment] 2019-01-28 17:47
In the log, you can see a line like "fixing up wheel ...". This is where we use auditwheel to copy linked libraries that are not in /usr/lib or standard system locations into the wheel. It looks like it's picking up a curl library that is not in BUILD_PREFIX, maybe one in an /opt directory. This could be an auditwheel bug.

**Comment by sgillies** [comment] 2019-01-28 20:48
Got a fix coming up for the linux wheels: I'm deleting the pre-existing 7.61 libs between downloading 7.54 and compiling it. I see `  3501408  2019-01-28 20:32   rasterio/.libs/libcurl-835381e7.so.4.4.0` in the logs and not `libcurl-*.so.4.5.0`, which is a good sign. I'll upload as a new build of 1.0.15 as soon as I test one.

Note that we're still using the system provided curl on OS X, so no HTTP/2. I'll need to amend my release announcement. Perhaps a future build can address this.

**Comment by sgillies** [comment] 2019-01-28 21:07
The linux wheels in https://travis-ci.com/sgillies/rasterio-wheels/builds/98868569 no longer warn about lack of HTTP/2 support, but they don't seem to use the protocol: if you set `CPL_CURL_VERBOSE=1` you will see that all the requests are HTTP/1.1. I think there may be an issue between GDAL and AWS.

**Comment by vincentsarago** [comment] 2019-01-28 21:11
@sgillies Yeah I've noticed that too but I assumed it was a `print` bug... we might ask Even about it

**Comment by vincentsarago** [comment] 2019-01-28 22:06
merci @sgillies

**Closed as completed** 2019-01-28 22:06 UTC
